(* DO NOT EDIT MANUALLY *)
(*  *)
(* generated by sqlgg a7a761f+M on 2025-11-26T14:56Z *)

module UsersOps (T : Sqlgg_traits.M) = struct

  module IO = Sqlgg_io.Blocking

  let create_users db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS users (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    user TEXT NOT NULL,\n\
    db_name TEXT NOT NULL,\n\
    hostname TEXT NOT NULL,\n\
    token TEXT NOT NULL\n\
)") T.no_params

  let add_user db ~id ~user ~db_name ~hostname ~token =
    let set_params stmt =
      let p = T.start_params stmt (5) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Text p user;
      T.set_param_Text p db_name;
      T.set_param_Text p hostname;
      T.set_param_Text p token;
      T.finish_params p
    in
    T.execute db ("INSERT INTO users VALUES (@id,@user,@db_name,@hostname,@token)") set_params

  let user_by_name db ~user_name callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~user:(T.get_column_Text stmt 1)
        ~db_name:(T.get_column_Text stmt 2)
        ~hostname:(T.get_column_Text stmt 3)
        ~token:(T.get_column_Text stmt 4)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Text p user_name;
      T.finish_params p
    in
    T.select db ("SELECT * FROM users u WHERE u.user = @user_name") set_params invoke_callback

  let remove_user db ~user_name =
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Text p user_name;
      T.finish_params p
    in
    T.execute db ("DELETE FROM users WHERE user = @user_name") set_params

  module Fold = struct
    let user_by_name db ~user_name callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~user:(T.get_column_Text stmt 1)
          ~db_name:(T.get_column_Text stmt 2)
          ~hostname:(T.get_column_Text stmt 3)
          ~token:(T.get_column_Text stmt 4)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p user_name;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT * FROM users u WHERE u.user = @user_name") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

  end (* module Fold *)
  
  module List = struct
    let user_by_name db ~user_name callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~user:(T.get_column_Text stmt 1)
          ~db_name:(T.get_column_Text stmt 2)
          ~hostname:(T.get_column_Text stmt 3)
          ~token:(T.get_column_Text stmt 4)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p user_name;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT * FROM users u WHERE u.user = @user_name") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

  end (* module List *)
end (* module UsersOps *)
