root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # args_bin = ["run-app -t new_tokens.json"]
  args_bin = ["turso"]
  bin = "./_build/default/bin/main.exe"
  # NOTE: official way to build the app is with the opam command
  # cmd = "opam exec -- dune build && sleep 1"
  cmd = "dune build && sleep 1"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["bin", "lib", "bench", "static"]
  include_ext = ["ml", "mli", "dune", "css", "png", "js", "ico"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
