# fly.toml app configuration file generated for unto on 2025-10-06T20:48:23+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'unto'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = "shared-cpu-1x"
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
