(* DO NOT EDIT MANUALLY *)
(*  *)
(* generated by sqlgg <unknown> on 2025-07-29T18:16Z *)

module DbOps (T : Sqlgg_traits.M) = struct

  module IO = Sqlgg_io.Blocking

  let create_athletes db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS athletes (\n\
    id INTEGER PRIMARY KEY,\n\
    firstname TEXT NOT NULL,\n\
    lastname TEXT NOT NULL,\n\
    city TEXT NOT NULL,\n\
    state TEXT NOT NULL,\n\
    country TEXT NOT NULL,\n\
    sex TEXT NOT NULL,\n\
    created_at TEXT NOT NULL,\n\
    weight FLOAT NOT NULL\n\
)") T.no_params

  let add_athlete db ~id ~firstname ~lastname ~city ~state ~country ~sex ~created_at ~weight =
    let set_params stmt =
      let p = T.start_params stmt (9) in
      T.set_param_Int p id;
      T.set_param_Text p firstname;
      T.set_param_Text p lastname;
      T.set_param_Text p city;
      T.set_param_Text p state;
      T.set_param_Text p country;
      T.set_param_Text p sex;
      T.set_param_Text p created_at;
      T.set_param_Float p weight;
      T.finish_params p
    in
    T.execute db ("INSERT INTO athletes VALUES (@id,@firstname,@lastname,@city,@state,@country,@sex,@created_at,@weight)") set_params

  let list_athletes db  callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~firstname:(T.get_column_Text stmt 1)
        ~lastname:(T.get_column_Text stmt 2)
        ~city:(T.get_column_Text stmt 3)
        ~state:(T.get_column_Text stmt 4)
        ~country:(T.get_column_Text stmt 5)
        ~sex:(T.get_column_Text stmt 6)
        ~created_at:(T.get_column_Text stmt 7)
        ~weight:(T.get_column_Float stmt 8)
    in
    T.select db ("SELECT * FROM athletes\n\
ORDER BY id") T.no_params invoke_callback

  let create_stats db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS stats (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    activity_id INTEGER NOT NULL,\n\
    data_points INTEGER NOT NULL,\n\
    moving_time INTEGER NOT NULL,\n\
    elapsed_time INTEGER NOT NULL,\n\
    distance REAL,               elev_gain INTEGER,           elev_loss INTEGER,           elev_high INTEGER,           elev_low INTEGER,            start_lat REAL,              start_lng REAL,              end_lat REAL,                end_lng REAL,                average_speed REAL,          max_speed REAL,              average_cadence INTEGER,     max_cadence INTEGER,         average_temp INTEGER,        average_heartrate INTEGER,     max_heartrate INTEGER,         average_power INTEGER,         max_power INTEGER,          \n\
    FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE CASCADE\n\
)") T.no_params

  let add_stats db ~id ~activity_id ~data_points ~moving_time ~elapsed_time ~distance ~elev_gain ~elev_loss ~elev_high ~elev_low ~start_lat ~start_lng ~end_lat ~end_lng ~average_speed ~max_speed ~average_cadence ~max_cadence ~average_temp ~average_heartrate ~max_heartrate ~average_power ~max_power =
    let set_params stmt =
      let p = T.start_params stmt (23) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p activity_id;
      T.set_param_Int p data_points;
      T.set_param_Int p moving_time;
      T.set_param_Int p elapsed_time;
      T.set_param_Float p distance;
      T.set_param_Int p elev_gain;
      T.set_param_Int p elev_loss;
      T.set_param_Int p elev_high;
      T.set_param_Int p elev_low;
      T.set_param_Float p start_lat;
      T.set_param_Float p start_lng;
      T.set_param_Float p end_lat;
      T.set_param_Float p end_lng;
      T.set_param_Float p average_speed;
      T.set_param_Float p max_speed;
      T.set_param_Int p average_cadence;
      T.set_param_Int p max_cadence;
      T.set_param_Int p average_temp;
      T.set_param_Int p average_heartrate;
      T.set_param_Int p max_heartrate;
      T.set_param_Int p average_power;
      T.set_param_Int p max_power;
      T.finish_params p
    in
    T.execute db ("INSERT INTO stats VALUES (@id,@activity_id,@data_points,@moving_time,@elapsed_time,@distance,@elev_gain,@elev_loss,@elev_high,@elev_low,@start_lat,@start_lng,@end_lat,@end_lng,@average_speed,@max_speed,@average_cadence,@max_cadence,@average_temp,@average_heartrate,@max_heartrate,@average_power,@max_power)") set_params

  let create_activities db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS activities (\n\
    id INTEGER PRIMARY KEY,\n\
    athlete_id INTEGER,\n\
    name TEXT NOT NULL,\n\
    sport_type TEXT NOT NULL,\n\
    start_date TEXT NOT NULL,\n\
    timezone TEXT NOT NULL,\n\
    map_id TEXT NOT NULL,\n\
    map_summary_polyline TEXT NOT NULL,\n\
    stats_id INTEGER NOT NULL,\n\
    FOREIGN KEY (athlete_id) REFERENCES athletes (id) ON DELETE CASCADE,\n\
    FOREIGN KEY (stats_id) REFERENCES stats (id) ON DELETE CASCADE\n\
)") T.no_params

  let add_activity db ~id ~athlete_id ~name ~sport_type ~start_date ~timezone ~map_id ~map_summary_polyline ~stats_id =
    let set_params stmt =
      let p = T.start_params stmt (9) in
      T.set_param_Int p id;
      T.set_param_Int p athlete_id;
      T.set_param_Text p name;
      T.set_param_Text p sport_type;
      T.set_param_Text p start_date;
      T.set_param_Text p timezone;
      T.set_param_Text p map_id;
      T.set_param_Text p map_summary_polyline;
      T.set_param_Int p stats_id;
      T.finish_params p
    in
    T.execute db ("INSERT INTO activities VALUES (@id,@athlete_id,@name,@sport_type,@start_date,@timezone,@map_id,@map_summary_polyline,@stats_id)") set_params

  let activities_after db ~start_date callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~athlete_id:(T.get_column_Int stmt 1)
        ~name:(T.get_column_Text stmt 2)
        ~sport_type:(T.get_column_Text stmt 3)
        ~start_date:(T.get_column_Text stmt 4)
        ~timezone:(T.get_column_Text stmt 5)
        ~map_id:(T.get_column_Text stmt 6)
        ~map_summary_polyline:(T.get_column_Text stmt 7)
        ~stats_id:(T.get_column_Int stmt 8)
        ~moving_time:(T.get_column_Int stmt 9)
        ~elapsed_time:(T.get_column_Int stmt 10)
        ~distance:(T.get_column_Float stmt 11)
        ~elev_gain:(T.get_column_Int stmt 12)
        ~elev_loss:(T.get_column_Int stmt 13)
        ~elev_high:(T.get_column_Int stmt 14)
        ~elev_low:(T.get_column_Int stmt 15)
        ~start_lat:(T.get_column_Float stmt 16)
        ~start_lng:(T.get_column_Float stmt 17)
        ~end_lat:(T.get_column_Float stmt 18)
        ~end_lng:(T.get_column_Float stmt 19)
        ~average_speed:(T.get_column_Float stmt 20)
        ~max_speed:(T.get_column_Float stmt 21)
        ~average_cadence:(T.get_column_Int stmt 22)
        ~max_cadence:(T.get_column_Int stmt 23)
        ~average_temp:(T.get_column_Int stmt 24)
        ~average_heartrate:(T.get_column_Int stmt 25)
        ~max_heartrate:(T.get_column_Int stmt 26)
        ~average_power:(T.get_column_Int stmt 27)
        ~max_power:(T.get_column_Int stmt 28)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Text p start_date;
      T.finish_params p
    in
    T.select db ("SELECT \n\
    a.*,\n\
    s.moving_time,\n\
    s.elapsed_time,\n\
    s.distance,\n\
    s.elev_gain,\n\
    s.elev_loss,\n\
    s.elev_high,\n\
    s.elev_low,\n\
    s.start_lat,\n\
    s.start_lng,\n\
    s.end_lat,\n\
    s.end_lng,\n\
    s.average_speed,\n\
    s.max_speed,\n\
    s.average_cadence,\n\
    s.max_cadence,\n\
    s.average_temp,\n\
    s.average_heartrate,\n\
    s.max_heartrate,\n\
    s.average_power,\n\
    s.max_power\n\
FROM activities a\n\
JOIN stats s ON a.stats_id = s.id\n\
WHERE a.start_date > @start_date") set_params invoke_callback

  let list_activities db  callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
    in
    T.select db ("SELECT id FROM activities") T.no_params invoke_callback

  let create_laps db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS laps (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    activity_id INTEGER NOT NULL,\n\
    lap_index INTEGER NOT NULL,\n\
    moving_time INTEGER NOT NULL,\n\
    start INTEGER NOT NULL,\n\
    len INTEGER NOT NULL,\n\
    stats_id INTEGER NOT NULL,\n\
    FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE CASCADE,\n\
    FOREIGN KEY (stats_id) REFERENCES stats (id) ON DELETE CASCADE\n\
)") T.no_params

  let add_lap db ~id ~activity_id ~lap_index ~moving_time ~start ~len ~stats_id =
    let set_params stmt =
      let p = T.start_params stmt (7) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p activity_id;
      T.set_param_Int p lap_index;
      T.set_param_Int p moving_time;
      T.set_param_Int p start;
      T.set_param_Int p len;
      T.set_param_Int p stats_id;
      T.finish_params p
    in
    T.execute db ("INSERT INTO laps VALUES (@id,@activity_id,@lap_index,@moving_time,@start,@len,@stats_id)") set_params

  let create_splits db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS splits (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    activity_id INTEGER NOT NULL,\n\
    split_index INTEGER NOT NULL,\n\
    start INTEGER NOT NULL,\n\
    len INTEGER NOT NULL,\n\
    stats_id INTEGER NOT NULL,\n\
    FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE CASCADE,\n\
    FOREIGN KEY (stats_id) REFERENCES stats (id) ON DELETE CASCADE\n\
)") T.no_params

  let add_split db ~id ~activity_id ~split_index ~start ~len ~stats_id =
    let set_params stmt =
      let p = T.start_params stmt (6) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p activity_id;
      T.set_param_Int p split_index;
      T.set_param_Int p start;
      T.set_param_Int p len;
      T.set_param_Int p stats_id;
      T.finish_params p
    in
    T.execute db ("INSERT INTO splits VALUES (@id,@activity_id,@split_index,@start,@len,@stats_id)") set_params

  module Fold = struct
    let list_athletes db  callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~firstname:(T.get_column_Text stmt 1)
          ~lastname:(T.get_column_Text stmt 2)
          ~city:(T.get_column_Text stmt 3)
          ~state:(T.get_column_Text stmt 4)
          ~country:(T.get_column_Text stmt 5)
          ~sex:(T.get_column_Text stmt 6)
          ~created_at:(T.get_column_Text stmt 7)
          ~weight:(T.get_column_Float stmt 8)
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT * FROM athletes\n\
ORDER BY id") T.no_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let activities_after db ~start_date callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~athlete_id:(T.get_column_Int stmt 1)
          ~name:(T.get_column_Text stmt 2)
          ~sport_type:(T.get_column_Text stmt 3)
          ~start_date:(T.get_column_Text stmt 4)
          ~timezone:(T.get_column_Text stmt 5)
          ~map_id:(T.get_column_Text stmt 6)
          ~map_summary_polyline:(T.get_column_Text stmt 7)
          ~stats_id:(T.get_column_Int stmt 8)
          ~moving_time:(T.get_column_Int stmt 9)
          ~elapsed_time:(T.get_column_Int stmt 10)
          ~distance:(T.get_column_Float stmt 11)
          ~elev_gain:(T.get_column_Int stmt 12)
          ~elev_loss:(T.get_column_Int stmt 13)
          ~elev_high:(T.get_column_Int stmt 14)
          ~elev_low:(T.get_column_Int stmt 15)
          ~start_lat:(T.get_column_Float stmt 16)
          ~start_lng:(T.get_column_Float stmt 17)
          ~end_lat:(T.get_column_Float stmt 18)
          ~end_lng:(T.get_column_Float stmt 19)
          ~average_speed:(T.get_column_Float stmt 20)
          ~max_speed:(T.get_column_Float stmt 21)
          ~average_cadence:(T.get_column_Int stmt 22)
          ~max_cadence:(T.get_column_Int stmt 23)
          ~average_temp:(T.get_column_Int stmt 24)
          ~average_heartrate:(T.get_column_Int stmt 25)
          ~max_heartrate:(T.get_column_Int stmt 26)
          ~average_power:(T.get_column_Int stmt 27)
          ~max_power:(T.get_column_Int stmt 28)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p start_date;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT \n\
    a.*,\n\
    s.moving_time,\n\
    s.elapsed_time,\n\
    s.distance,\n\
    s.elev_gain,\n\
    s.elev_loss,\n\
    s.elev_high,\n\
    s.elev_low,\n\
    s.start_lat,\n\
    s.start_lng,\n\
    s.end_lat,\n\
    s.end_lng,\n\
    s.average_speed,\n\
    s.max_speed,\n\
    s.average_cadence,\n\
    s.max_cadence,\n\
    s.average_temp,\n\
    s.average_heartrate,\n\
    s.max_heartrate,\n\
    s.average_power,\n\
    s.max_power\n\
FROM activities a\n\
JOIN stats s ON a.stats_id = s.id\n\
WHERE a.start_date > @start_date") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let list_activities db  callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT id FROM activities") T.no_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

  end (* module Fold *)
  
  module List = struct
    let list_athletes db  callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~firstname:(T.get_column_Text stmt 1)
          ~lastname:(T.get_column_Text stmt 2)
          ~city:(T.get_column_Text stmt 3)
          ~state:(T.get_column_Text stmt 4)
          ~country:(T.get_column_Text stmt 5)
          ~sex:(T.get_column_Text stmt 6)
          ~created_at:(T.get_column_Text stmt 7)
          ~weight:(T.get_column_Float stmt 8)
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT * FROM athletes\n\
ORDER BY id") T.no_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let activities_after db ~start_date callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~athlete_id:(T.get_column_Int stmt 1)
          ~name:(T.get_column_Text stmt 2)
          ~sport_type:(T.get_column_Text stmt 3)
          ~start_date:(T.get_column_Text stmt 4)
          ~timezone:(T.get_column_Text stmt 5)
          ~map_id:(T.get_column_Text stmt 6)
          ~map_summary_polyline:(T.get_column_Text stmt 7)
          ~stats_id:(T.get_column_Int stmt 8)
          ~moving_time:(T.get_column_Int stmt 9)
          ~elapsed_time:(T.get_column_Int stmt 10)
          ~distance:(T.get_column_Float stmt 11)
          ~elev_gain:(T.get_column_Int stmt 12)
          ~elev_loss:(T.get_column_Int stmt 13)
          ~elev_high:(T.get_column_Int stmt 14)
          ~elev_low:(T.get_column_Int stmt 15)
          ~start_lat:(T.get_column_Float stmt 16)
          ~start_lng:(T.get_column_Float stmt 17)
          ~end_lat:(T.get_column_Float stmt 18)
          ~end_lng:(T.get_column_Float stmt 19)
          ~average_speed:(T.get_column_Float stmt 20)
          ~max_speed:(T.get_column_Float stmt 21)
          ~average_cadence:(T.get_column_Int stmt 22)
          ~max_cadence:(T.get_column_Int stmt 23)
          ~average_temp:(T.get_column_Int stmt 24)
          ~average_heartrate:(T.get_column_Int stmt 25)
          ~max_heartrate:(T.get_column_Int stmt 26)
          ~average_power:(T.get_column_Int stmt 27)
          ~max_power:(T.get_column_Int stmt 28)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p start_date;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT \n\
    a.*,\n\
    s.moving_time,\n\
    s.elapsed_time,\n\
    s.distance,\n\
    s.elev_gain,\n\
    s.elev_loss,\n\
    s.elev_high,\n\
    s.elev_low,\n\
    s.start_lat,\n\
    s.start_lng,\n\
    s.end_lat,\n\
    s.end_lng,\n\
    s.average_speed,\n\
    s.max_speed,\n\
    s.average_cadence,\n\
    s.max_cadence,\n\
    s.average_temp,\n\
    s.average_heartrate,\n\
    s.max_heartrate,\n\
    s.average_power,\n\
    s.max_power\n\
FROM activities a\n\
JOIN stats s ON a.stats_id = s.id\n\
WHERE a.start_date > @start_date") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let list_activities db  callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT id FROM activities") T.no_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

  end (* module List *)
end (* module DbOps *)
